package printing

// Command is one decoded ESC/POS instruction — either a run of printable
// text/line-feeds, or a barcode print request with its symbology and raw
// data separated out. Decode's job is entirely to make Builder's output
// assertable in tests without a real printer: a test can check "the
// generated bytes contain the product's name" or "the barcode command
// carries symbology EAN-13 with this exact code" against the same bytes
// a physical printer would receive, instead of trusting the Builder call
// sequence looked right.
type Command struct {
	Text             string // set when this is a text/line-feed run
	IsBarcode        bool
	BarcodeSymbology byte
	BarcodeData      string
}

// Decode walks a byte stream produced by Builder and recovers the
// sequence of text runs and barcode commands in it, skipping over
// formatting-only commands (init, align, bold, double-size, cut, barcode
// height/width/HRI) that don't carry inspectable content. It only
// understands the commands this package's Builder actually emits — it is
// a verification tool for this driver, not a general ESC/POS parser.
func Decode(data []byte) []Command {
	var cmds []Command
	var text []byte
	flush := func() {
		if len(text) > 0 {
			cmds = append(cmds, Command{Text: string(text)})
			text = nil
		}
	}

	i := 0
	for i < len(data) {
		switch {
		case matches(data, i, "\x1B\x40"): // ESC @ (init)
			i += 2
		case matches(data, i, "\x1B\x61"): // ESC a <n>
			i += 3
		case matches(data, i, "\x1B\x45"): // ESC E <n>
			i += 3
		case matches(data, i, "\x1D\x21"): // GS ! <n>
			i += 3
		case matches(data, i, "\x1D\x56"): // GS V <n>
			i += 3
		case matches(data, i, "\x1D\x68"): // GS h <n>
			i += 3
		case matches(data, i, "\x1D\x77"): // GS w <n>
			i += 3
		case matches(data, i, "\x1D\x48"): // GS H <n>
			i += 3
		case matches(data, i, "\x1D\x6B"): // GS k <m> <n> <data...>
			flush()
			m := data[i+2]
			n := int(data[i+3])
			start := i + 4
			end := start + n
			cmds = append(cmds, Command{IsBarcode: true, BarcodeSymbology: m, BarcodeData: string(data[start:end])})
			i = end
		default:
			text = append(text, data[i])
			i++
		}
	}
	flush()
	return cmds
}

func matches(data []byte, i int, prefix string) bool {
	if i+len(prefix) > len(data) {
		return false
	}
	return string(data[i:i+len(prefix)]) == prefix
}
